# Site settings
title: Denielll
description: my personal web > <
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br



# User settings
username: Daniel Chang
user_description_1: Hi ! This is SHU-HAO ( Daniel ), CHANG. I'm an undergrad majoring in Economics from National Chengchi University, Taipei, Taiwan. I like films, photography and badminton, and I am a techie :)))  
user_description_2: Also, I'm passionate about playing with data, and delivering insights in data ! Feel free to contact me by clicking the mail icon above.
user_title: Economics, Statistics, Computer Science
email: deniel3678@gmail.com
blog: http://denielll.logdown.com/
twitter_username: deniellld
github_username:  denielll
# gplus_username:  deniel3678



# skill
skill_1: Python for data visualization, web crawling, and machine learning. Relational and NoSQL database setup, index building and queries.
skill_2: A liitle web frontend, specifically D3.js, for data visualization. A little web backend with Python Flask for writing RESTFUL API.
skill_3: Basic programming skill of C. Linux. Tools such as Git, AWS, GCP, Trello,...etc.



# projects
project_10: Collaborated with surgeons, fire fighters, and other teammates in creating Decision Support System, which is used to faciliate the process of, say,  an injured person sent to a suitable hospital. I worked as a backend engineer writing RESTFUL API.

project_11: Joined a team of 10 exploring 33 hospitals database in Taiwan and creating website for the promotion of awareness and prevention of trauma. I worked as a backend engineer deploying ML models and writing RESTFUL API. I also created plots on the website with D3.js.

project_12: Made prediction for a bank, Mckinsey&Company's customer, on whether the applications for the loans would be apporved. Ranked around top 30% among 600+ participants in this game.

project_13: Teamed up with 5 creating an Android & Web App faciliating direct information exchange between customers and farmers. We won the Best Popularity Award. I worked as a web crawling developer collecting farmers' data.








# Google-analytics
google-analytics:
  id: ""


exclude: ['package.json', 'src' , 'node_modules']
